wandb_version: 1

batch_size:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 3
optimizer:
  desc: null
  value: SGD
job_name:
  desc: null
  value: Local
fold:
  desc: null
  value: 0
input:
  desc: null
  value: Both
loss:
  desc: null
  value: focal
features:
  desc: null
  value:
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
patch_size:
  desc: null
  value:
  - 192
  - 192
  - 64
nbr_batch_epoch:
  desc: null
  value: 20
nesterov:
  desc: null
  value: false
val_size_epoch:
  desc: null
  value: 1.0
weigth_decay:
  desc: null
  value: 3.0000000000000004e-05
scheduler:
  desc: null
  value: false
value_momentum:
  desc: null
  value: 0.99
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699287185.331705
    t:
      1:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.15.0
      8:
      - 5
